export const quotes = [
  { text: "Everything you've ever wanted is sitting on the other side of fear.", author: "George Addair" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { text: "I didn't get there by wishing for it or hoping for it, but by working for it.", author: "Estée Lauder" },
  { text: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho" },
  { text: "Just one small positive thought in the morning can change your whole day.", author: "Dalai Lama" },
  { text: "You have to believe in yourself when no one else does.", author: "Serena Williams" },
  { text: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Life is about making an impact, not making an income.", author: "Kevin Kruse" },
  { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
  { text: "You see, in life, lots of people know what to do, but few actually do what they know. Knowing is not enough! You must take action.", author: "Tony Robbins" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
];
export const backgroundImages = [
  "images/background/1.jpg",
  "images/background/2.jpg",
  "images/background/3.jpg",
  "images/background/4.jpg",
  "images/background/5.jpg",
  "images/background/6.jpg",
  "images/background/7.jpg",
  "images/background/8.jpg",
  "images/background/9.jpg",
  "images/background/10.jpg",
  "images/background/11.jpg",
  "images/background/12.jpg",
  "images/background/13.jpg",
  "images/background/14.jpg",
  "images/background/15.jpg",
  "images/background/16.jpg",
  "images/background/17.jpg",
  "images/background/18.jpg",
  "images/background/19.jpg",
  "images/background/20.jpg",

  // add as many as you have
];